// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "gavin",
            "url": "http://github.com/sfshf",
            "email": "sfshf@github.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/sfshf/sprout/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/casbin/priority": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get predefined priority range of roles.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "casbin"
                ],
                "summary": "Get predefined priority range of roles.",
                "operationId": "casbin-role-priority",
                "responses": {
                    "1000": {
                        "description": "feasible and predictable errors.",
                        "schema": {
                            "type": "error"
                        }
                    },
                    "2000": {
                        "description": "minimum and maximum value of the predefined priority range.",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/picCaptcha": {
            "get": {
                "description": "Get a new picture captcha id and base64 string of the picture, and delete the obsolete captcha of the obsolete_id, if has.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Get a picture captcha.",
                "operationId": "get-pic-captcha",
                "parameters": [
                    {
                        "type": "string",
                        "description": "an obsolete captcha id.",
                        "name": "obsolete_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "1000": {
                        "description": "feasible and predictable errors.",
                        "schema": {
                            "type": "error"
                        }
                    },
                    "2000": {
                        "description": "captcha id and picture.",
                        "schema": {
                            "$ref": "#/definitions/bll.GetPicCaptchaResp"
                        }
                    }
                }
            }
        },
        "/picCaptchaAnswer": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get the answer code of a picture captcha with the captcha id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Get the answer code of a picture captcha.",
                "operationId": "get-pic-captcha-answer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "a captcha id.",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1000": {
                        "description": "Invalid Token, Invalid Captcha, Unauthorized, or other errors.",
                        "schema": {
                            "type": "error"
                        }
                    },
                    "2000": {
                        "description": "captcha answer code",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/signIn": {
            "patch": {
                "description": "Sign in with account and password, supporting picture captcha authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Sign in.",
                "operationId": "sign-in",
                "parameters": [
                    {
                        "description": "required attributes to sign in.",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bll.SignInReq"
                        }
                    }
                ],
                "responses": {
                    "1000": {
                        "description": "feasible and predictable errors.",
                        "schema": {
                            "type": "error"
                        }
                    },
                    "2000": {
                        "description": "sign in token and expiry time.",
                        "schema": {
                            "$ref": "#/definitions/bll.SignInResp"
                        }
                    }
                }
            }
        },
        "/signOff/:id": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Sign off the session account, or some specific account only by root account.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Sign off.",
                "operationId": "sign-off",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of the account to sign off.",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "1000": {
                        "description": "feasible and predictable errors.",
                        "schema": {
                            "type": "error"
                        }
                    },
                    "2000": {
                        "description": "successful action.",
                        "schema": {
                            "type": "null"
                        }
                    }
                }
            }
        },
        "/signOut": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Sign out the session account.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Sign out.",
                "operationId": "sign-out",
                "responses": {
                    "1000": {
                        "description": "feasible and predictable errors.",
                        "schema": {
                            "type": "error"
                        }
                    },
                    "2000": {
                        "description": "successful action.",
                        "schema": {
                            "type": "null"
                        }
                    }
                }
            }
        },
        "/signUp": {
            "post": {
                "description": "Sign up a new staff account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Sign up.",
                "operationId": "sign-up",
                "parameters": [
                    {
                        "description": "required attributes to sign up.",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bll.SignUpReq"
                        }
                    }
                ],
                "responses": {
                    "1000": {
                        "description": "feasible and predictable errors.",
                        "schema": {
                            "type": "error"
                        }
                    },
                    "2000": {
                        "description": "successful action.",
                        "schema": {
                            "type": "null"
                        }
                    }
                }
            }
        },
        "/staff": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a list of staff accounts.",
                "tags": [
                    "staff"
                ],
                "summary": "Get a list of staff accounts.",
                "operationId": "staff-list",
                "parameters": [
                    {
                        "type": "string",
                        "name": "account",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "gender",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "lastSignInIp",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "lastSignInTimeBegin",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "lastSignInTimeEnd",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "orderBy",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "perPage",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "phone",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "name": "signIn",
                        "in": "query"
                    }
                ],
                "responses": {
                    "1000": {
                        "description": "feasible and predictable errors.",
                        "schema": {
                            "type": "error"
                        }
                    },
                    "2000": {
                        "description": "staff list.",
                        "schema": {
                            "$ref": "#/definitions/bll.StaffListResp"
                        }
                    }
                }
            }
        },
        "/staff/:id": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get the profile of a staff account.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Get infos of a staff account.",
                "operationId": "staff-profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of the staff account.",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "1000": {
                        "description": "feasible and predictable errors.",
                        "schema": {
                            "type": "error"
                        }
                    },
                    "2000": {
                        "description": "profile of the staff.",
                        "schema": {
                            "$ref": "#/definitions/bll.ProfileResp"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update all updatable attributes of a staff account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Update attributes of a staff.",
                "operationId": "staff-update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of the staff account to update.",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "attributes to update.",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bll.StaffUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "1000": {
                        "description": "feasible and predictable errors.",
                        "schema": {
                            "type": "error"
                        }
                    },
                    "2000": {
                        "description": "successful action.",
                        "schema": {
                            "type": "null"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "bll.GetPicCaptchaResp": {
            "type": "object",
            "properties": {
                "picCaptchaB64s": {
                    "type": "string"
                },
                "picCaptchaId": {
                    "type": "string"
                }
            }
        },
        "bll.ProfileResp": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "lastSignInIp": {
                    "type": "string"
                },
                "lastSignInTime": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                },
                "realName": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "signInIpWhiteList": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "signUpAt": {
                    "type": "integer"
                }
            }
        },
        "bll.SignInReq": {
            "type": "object",
            "required": [
                "picCaptchaAnswer",
                "picCaptchaId"
            ],
            "properties": {
                "account": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "picCaptchaAnswer": {
                    "type": "string"
                },
                "picCaptchaId": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "bll.SignInResp": {
            "type": "object",
            "properties": {
                "expiresAt": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "bll.SignUpReq": {
            "type": "object",
            "required": [
                "email",
                "timestamp"
            ],
            "properties": {
                "account": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "realName": {
                    "type": "string"
                },
                "signInIpWhitelist": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "bll.StaffListResp": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "bll.StaffUpdateReq": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "signInIpWhitelist": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.1-beta",
	Host:        "localhost:8000",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "Govern APIs",
	Description: "This is a back-end government app.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
