# https://docs.travis-ci.com/user/languages/go/
language: go
go:
  - 1.16.x

go_import_path: github.com/sfshf/sprout/app/govern

sudo: false

env:
  GO111MODULE=on

before_install:
  - go get -t -v ./...

script:
  - go test -cover -race -coverprofile=coverage.out -covermode=atomic

# after_success:
#   - go tool cover -html=coverage.out