// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
	"github.com/sfshf/sprout/app/govern/api"
	"github.com/sfshf/sprout/app/govern/bll"
	"github.com/sfshf/sprout/app/govern/ginx/router"
	"github.com/sfshf/sprout/repo"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func NewApp(ctx context.Context) (*App, func(), error) {
	engine := router.NewRouter()
	database, err := NewMongoDB(ctx)
	if err != nil {
		return nil, nil, err
	}
	staff := repo.NewStaffRepo(ctx, database)
	jwtAuth := NewAuth()
	captcha := NewPictureCaptcha()
	bllStaff := bll.NewStaff(staff, jwtAuth, captcha)
	apiStaff := api.NewStaff(bllStaff)
	casbin := repo.NewCasbinRepo(ctx, database)
	bllCasbin := bll.NewCasbin(casbin)
	apiCasbin := api.NewCasbin(bllCasbin)
	user := repo.NewUserRepo(ctx, database)
	bllUser := bll.NewUser(user)
	apiUser := api.NewUser(bllUser)
	accessLog := repo.NewAccessLogRepo(ctx, database)
	syncedEnforcer, cleanup := NewCasbin(ctx, casbin)
	app := &App{
		Router:        engine,
		StaffApi:      apiStaff,
		CasbinApi:     apiCasbin,
		UserApi:       apiUser,
		StaffRepo:     staff,
		CasbinRepo:    casbin,
		UserRepo:      user,
		AccessLogRepo: accessLog,
		Auther:        jwtAuth,
		Enforcer:      syncedEnforcer,
		PicCaptcha:    captcha,
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

var (
	ApiSet  = wire.NewSet(api.NewStaff, api.NewCasbin, api.NewUser)
	BllSet  = wire.NewSet(bll.NewStaff, bll.NewCasbin, bll.NewUser)
	RepoSet = wire.NewSet(repo.NewStaffRepo, repo.NewCasbinRepo, repo.NewUserRepo, repo.NewAccessLogRepo)
	AppSet  = wire.NewSet(
		NewAuth,
		NewCasbin,
		NewPictureCaptcha,
		NewMongoDB,
		RepoSet,
		BllSet,
		ApiSet, router.NewRouter, wire.Struct(new(App), "*"),
	)
)
