// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
	"github.com/sfshf/sprout/app/govern/api"
	"github.com/sfshf/sprout/app/govern/bll"
	"github.com/sfshf/sprout/cache"
	"github.com/sfshf/sprout/repo"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func NewApp(ctx context.Context) (*App, func(), error) {
	database, cleanup, err := NewMongoDB(ctx)
	if err != nil {
		return nil, nil, err
	}
	staff := repo.NewStaffRepo(ctx, database)
	client, cleanup2, err := NewRedisDB(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	redisCache := cache.NewRedisCache(client)
	jwtAuth := NewAuth()
	captcha := NewPictureCaptcha()
	bllStaff := bll.NewStaff(staff, redisCache, jwtAuth, captcha)
	apiStaff := api.NewStaff(bllStaff)
	casbin := repo.NewCasbinRepo(ctx, database)
	enforcer := NewCasbin(ctx, casbin)
	bllCasbin := bll.NewCasbin(enforcer, staff)
	apiCasbin := api.NewCasbin(bllCasbin)
	accessLog := repo.NewAccessLogRepo(ctx, database)
	bllAccessLog := bll.NewAccessLog(accessLog)
	apiAccessLog := api.NewAccessLog(bllAccessLog)
	user := repo.NewUserRepo(ctx, database)
	bllUser := bll.NewUser(user)
	apiUser := api.NewUser(bllUser)
	cacheCache, cleanup3, err := NewCache(ctx)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	memoryCache := cache.NewMemoryCache(cacheCache)
	logger, err := NewLogger(accessLog)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	engine := NewRouter(ctx, logger)
	app := &App{
		StaffApi:      apiStaff,
		CasbinApi:     apiCasbin,
		AccessLogApi:  apiAccessLog,
		UserApi:       apiUser,
		StaffRepo:     staff,
		CasbinRepo:    casbin,
		UserRepo:      user,
		AccessLogRepo: accessLog,
		RedisCache:    redisCache,
		MemoryCache:   memoryCache,
		Router:        engine,
		Auther:        jwtAuth,
		Enforcer:      enforcer,
		PicCaptcha:    captcha,
		Logger:        logger,
	}
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var (
	ApiSet   = wire.NewSet(api.NewStaff, api.NewCasbin, api.NewAccessLog, api.NewUser)
	BllSet   = wire.NewSet(bll.NewStaff, bll.NewCasbin, bll.NewAccessLog, bll.NewUser)
	RepoSet  = wire.NewSet(repo.NewStaffRepo, repo.NewCasbinRepo, repo.NewAccessLogRepo, repo.NewUserRepo)
	CacheSet = wire.NewSet(cache.NewMemoryCache, cache.NewRedisCache)
	AppSet   = wire.NewSet(
		NewAuth,
		NewCasbin,
		NewPictureCaptcha,
		NewMongoDB,
		NewRedisDB,
		NewCache,
		NewLogger,
		RepoSet,
		CacheSet,
		BllSet,
		ApiSet,
		NewRouter, wire.Struct(new(App), "*"),
	)
)
